### ISSUE TITLE
请问能否改成使用Notion API token？

### ISSUE THREAD

**Issue by yunchong-song** [qumuchegi/notion-docsify#3]
这个project非常棒！非常简单易操作，想问一下能否加一下使用Notion API token，而不是直接把页面设置为public的选项呢，毕竟有些页面不太想被公开检索到，但使用Notion API token就可以指定让拥有token的程序访问

**Comment by qumuchegi** [comment]
感谢反馈，很快会改用 token

**Comment by qumuchegi** [comment]
可以使用 token 了，不过需要定期更新 token，后面再想想怎么使用 Notion integration token，能不能不需要手动更新 token

**Comment by yunchong-song** [comment]
> 可以使用 token 了，不过需要定期更新 token，后面再想想怎么使用 Notion integration token，能不能不需要手动更新 token

好的，感谢！
